const actions = {
    FETCH_CONVERSATION_BY_USERID: 'FETCH_CONVERSATION_BY_USERID',
    FETCH_CONVERSATION_BY_USERID_SUCCESS: 'FETCH_CONVERSATION_BY_USERID_SUCCESS',
    FETCH_CONVERSATION_BY_USERID_LOADING: 'FETCH_CONVERSATION_BY_USERID_LOADING',
    FETCH_CONVERSATION_BY_USERID_FAILED: 'FETCH_CONVERSATION_BY_USERID_FAILED',
    FETCH_CONVERSATION_BY_USERID_RESET: 'FETCH_CONVERSATION_BY_USERID_RESET',

    CREATE_CONVERSATION: "CREATE_CONVERSATION",
    CREATE_CONVERSATION_SUCCESS: "CREATE_CONVERSATION_SUCCESS",
    CREATE_CONVERSATION_LOADING: "CREATE_CONVERSATION_LOADING",
    CREATE_CONVERSATION_FAILED: "CREATE_CONVERSATION_FAILED",
    CREATE_CONVERSATION_RESET: "CREATE_CONVERSATION_RESET",

    FETCH_ALL_CONVERSTION: "FETCH_ALL_CONVERSTION",
    FETCH_ALL_CONVERSTION_SUCCESS: "FETCH_ALL_CONVERSTION_SUCCESS",
    FETCH_ALL_CONVERSTION_LOADING: "FETCH_ALL_CONVERSTION_LOADING",
    FETCH_ALL_CONVERSTION_FAILED: "FETCH_ALL_CONVERSTION_FAILED",
    FETCH_ALL_CONVERSTION_RESET: "FETCH_ALL_CONVERSTION_RESET",

    fetchConversationByUserId: (payload) => ({
        type: actions.FETCH_CONVERSATION_BY_USERID,
        payload
    }),
    fetchConversationByUserIdReset: () => ({
        type: actions.FETCH_CONVERSATION_BY_USERID_RESET,
    }),
    createConversation: (payload) => ({
        type: actions.CREATE_CONVERSATION,
        payload
    }),
    createConversationReset: () => ({
        type: actions.CREATE_CONVERSATION_RESET,
    }),
    fetchAllConversation: () => ({
        type: actions.FETCH_ALL_CONVERSTION,
    }),
    fetchAllConversationReset: () => ({
        type: actions.CREATE_CONVERSATION_RESET,
    }),
}
  
export default actions;
  