const actions = {
    FETCH_CONVERSATION_BY_USERID: 'FETCH_CONVERSATION_BY_USERID',
    FETCH_CONVERSATION_BY_USERID_SUCCESS: 'FETCH_CONVERSATION_BY_USERID_SUCCESS',
    FETCH_CONVERSATION_BY_USERID_LOADING: 'FETCH_CONVERSATION_BY_USERID_LOADING',
    FETCH_CONVERSATION_BY_USERID_FAILED: 'FETCH_CONVERSATION_BY_USERID_FAILED',
    FETCH_CONVERSATION_BY_USERID_RESET: 'FETCH_CONVERSATION_BY_USERID_RESET',

    CREATE_CONVERSATION: "CREATE_CONVERSATION",
    CREATE_CONVERSATION_SUCCESS: "CREATE_CONVERSATION_SUCCESS",
    CREATE_CONVERSATION_LOADING: "CREATE_CONVERSATION_LOADING",
    CREATE_CONVERSATION_FAILED: "CREATE_CONVERSATION_FAILED",
    CREATE_CONVERSATION_RESET: "CREATE_CONVERSATION_RESET",

    FETCH_ALL_CONVERSTION: "FETCH_ALL_CONVERSTION",
    FETCH_ALL_CONVERSTION_SUCCESS: "FETCH_ALL_CONVERSTION_SUCCESS",
    FETCH_ALL_CONVERSTION_LOADING: "FETCH_ALL_CONVERSTION_LOADING",
    FETCH_ALL_CONVERSTION_FAILED: "FETCH_ALL_CONVERSTION_FAILED",
    FETCH_ALL_CONVERSTION_RESET: "FETCH_ALL_CONVERSTION_RESET",

    ADD_PARTICIPANTS: "ADD_PARTICIPANTS",
    ADD_PARTICIPANTS_SUCCESS: "ADD_PARTICIPANTS_SUCCESS",
    ADD_PARTICIPANTS_LOADING: "ADD_PARTICIPANTS_LOADING",
    ADD_PARTICIPANTS_FAILED: "ADD_PARTICIPANTS_FAILED",
    ADD_PARTICIPANTS_RESET: "ADD_PARTICIPANTS_RESET",

    REMOVE_PARTICIPANTS: "REMOVE_PARTICIPANTS",
    REMOVE_PARTICIPANTS_SUCCESS: "REMOVE_PARTICIPANTS_SUCCESS",
    REMOVE_PARTICIPANTS_LOADING: "REMOVE_PARTICIPANTS_LOADING",
    REMOVE_PARTICIPANTS_FAILED: "REMOVE_PARTICIPANTS_FAILED",
    REMOVE_PARTICIPANTS_RESET: "REMOVE_PARTICIPANTS_RESET",

    UPDATE_CONVERSATION: "UPDATE_CONVERSATION",
    UPDATE_CONVERSATION_SUCCESS: "UPDATE_CONVERSATION_SUCCESS",
    UPDATE_CONVERSATION_LOADING: "UPDATE_CONVERSATION_LOADING",
    UPDATE_CONVERSATION_FAILED: "UPDATE_CONVERSATION_FAILED",
    UPDATE_CONVERSATION_RESET: "UPDATE_CONVERSATION_RESET",

    fetchConversationByUserId: (payload) => ({
        type: actions.FETCH_CONVERSATION_BY_USERID,
        payload
    }),
    fetchConversationByUserIdReset: () => ({
        type: actions.FETCH_CONVERSATION_BY_USERID_RESET,
    }),
    createConversation: (payload) => ({
        type: actions.CREATE_CONVERSATION,
        payload
    }),
    createConversationReset: () => ({
        type: actions.CREATE_CONVERSATION_RESET,
    }),
    fetchAllConversation: () => ({
        type: actions.FETCH_ALL_CONVERSTION,
    }),
    fetchAllConversationReset: () => ({
        type: actions.CREATE_CONVERSATION_RESET,
    }),
    addParticipants: (payload) => ({
        type: actions.ADD_PARTICIPANTS,
        payload
    }),
    addParticipantsReset: () => ({
        type: actions.ADD_PARTICIPANTS_RESET,
    }),
    removeParticipants: (payload) => ({
        type: actions.REMOVE_PARTICIPANTS,
        payload
    }),
    removeParticipantsReset: () => ({
        type: actions.REMOVE_PARTICIPANTS_RESET,
    }),
    updateConversation: (payload) => ({
        type: actions.UPDATE_CONVERSATION,
        payload
    }),
    updateConversationReset: () => ({
        type: actions.UPDATE_CONVERSATION_RESET,
    }),
}
  
export default actions;
  